### ISSUE TITLE
vega-lite to vega-zero

### ISSUE THREAD

**Issue by vision-zhao** [Thanksyy/Vega-Zero#1]
Hello. Is it possible for me to convert Vega-Lite specification to Vega-Zero grammar?
If you can offer any advice, that will be much appreciated!

**Comment by Thanksyy** [comment]
Hi, converting Vega-Lite Spec to Vega-Zero grammar is quite straightforward. We just need to scan each KEYWORD of Vega-Lite and EXTRACT the VALUES under KEYWORD. Next, we fill these VALUES to the corresponding KEYWORD part of the Vega-Zero template. :) The Figure in the README is an example.  @vision-zhao
